# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default='enabled', max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('usState', models.CharField(max_length=50)),
                ('zipCode', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.Enterprise')),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
